name: Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Deployment
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          VERSION: ${{ vars.APP_VERSION }}
        run: |
          echo "deployment steps"
          echo "APP VERSION: $VERSION, Setting database from $DB_HOST with password: $DB_PASSWORD (Do not log secrets like this)"
        # ...deployment-specific steps
