name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
    - uses: actions/checkout@v3
    - name: deploy
        # ...deployment-specific steps
