name: Label steps

on:
  pull_request:
    branches: [ master ]
    types: ['labeled']
  workflow_dispatch:
    inputs:
      version:
        description: Flow version
        type: choice
        required: true
        default: "v3"
        options:
          - "v1"
          - "v2"
          - "v3"
      app-name:
        description: App Name (Optional, defaults to anyroad-<branch>)
        type: string
        default: "test App"
        required: false


jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge to Integration branch
    if: github.event.label.name == 'test-label'
    steps:
      - name: Test label echo
        run: |
          echo "Test label added on ${{ github.event.pull_request.head.ref }}"
