name: Label steps

on:
  pull_request:
    branches: [ master ]
    types: ['labeled']

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge to Integration branch
    if: github.event.label.name == 'test-label'
    steps:
      - name: Test label echo
        run: |
          echo "Test label added on ${{ github.event.pull_request.head.ref }}"
      - name: Slack Notification
        run: |
          echo "Send slack notifications"
